Test

diff --git a/.github/workflows/blockMerge.yml b/.github/workflows/blockMerge.yml
--- a/.github/workflows/blockMerge.yml
+++ b/.github/workflows/blockMerge.yml
@@ -13,12 +13,13 @@ jobs:
   fail-for-do-not-merge:
     runs-on: ubuntu-latest
     steps:
-      - name: Fail if PR is labeled with do not merge
+      - name: Check if PR is labeled with do not merge
+        id: check-label
         run: |
           if contains(github.event.pull_request.labels.*.name, 'DO NOT MERGE'); then
-             echo "This PR can't be merged, due to the 'DO NOT MERGE' label."
-             exit 1
+            echo "This PR can't be merged, due to the 'DO NOT MERGE' label."
+            exit 1
           else
-             echo "This PR is not labeled with 'DO NOT MERGE'. It can be merged."
-             exit 0
+            echo "This PR is not labeled with 'DO NOT MERGE'. It can be merged."
+            exit 0
           fi
